owner: restuillahi
repo: uptime

sites:
  - name: DNS Primary
    url: $DNS_PRIMARY
    port: 53
    check: "tcp-ping"
  - name: Homepage Primary
    url: $HOMEPAGE_PRIMARY
    port: 443
    check: "tcp-ping"
  - name: Homepage Secondary
    url: $HOMEPAGE_SECONDARY
    port: 443
    check: "tcp-ping"
  - name: Cloud Storage
    url: $CLOUD_STORAGE_URL
  - name: VPN
    url: $VPN_GATEWAY_URL
  - name: VPN Primary
    url: $VPN_GATEWAY_PRIMARY
    port: $VPN_PORT
    check: "tcp-ping"
  - name: VPN Secondary
    url: $VPN_GATEWAY_SECONDARY
    port: $VPN_PORT
    check: "tcp-ping"
    
status-website:
  baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Uptime
