owner: restuillahi
repo: uptime

sites:
  - name: DNS Primary
    url: $DNS_PRIMARY
    port: 53
    check: "tcp-ping"
  - name: Homepage
    url: $HOMEPAGE_URL
  - name: ISP 1
    url: $ISP_1
    port: 80
    check: "tcp-ping"
  - name: ISP 2
    url: $ISP_2
    port: 80
    check: "tcp-ping"
  - name: ISP 3
    url: $ISP_3
    port: 80
    check: "tcp-ping"
  - name: Cloud Storage
    url: $CLOUD_STORAGE_URL
  - name: VPN
    url: $VPN_GATEWAY_URL
  - name: VPN Primary
    url: $VPN_GATEWAY_PRIMARY
    port: $VPN_PORT
    check: "tcp-ping"
  - name: VPN Secondary
    url: $VPN_GATEWAY_SECONDARY
    port: $VPN_PORT
    check: "tcp-ping"
    
status-website:
  baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Uptime
