# Change these first
owner: restuillahi # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: Homepage
    url: $HOMEPAGE_URL
  - name: Cloud Storage
    url: $CLOUD_STORAGE_URL
  - name: VPN
    url: $VPN_GATEWAY_URL
  - name: VPN Primary
    url: $VPN_GATEWAY_PRIMARY
    port: $VPN_PORT
    check: "tcp-ping"
  - name: VPN Secondary
    url: $VPN_GATEWAY_SECONDARY
    port: $VPN_PORT
    check: "tcp-ping"

status-website:
  baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Uptime
